"""Add ride payment fields

Revision ID: cd2e70865522
Revises: 
Create Date: 2026-06-22 22:49:35.820204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2e70865522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full name of the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address (unique)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Phone number for ride coordination'),
    sa.Column('role', sa.Enum('RIDER', 'DRIVER', 'ADMIN', name='user_role_enum'), nullable=False, comment='User type: rider, driver, or admin'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique ride identifier'),
    sa.Column('rider_id', sa.UUID(), nullable=False, comment='Rider who requested the ride'),
    sa.Column('driver_id', sa.UUID(), nullable=True, comment='Assigned driver (null until accepted)'),
    sa.Column('status', sa.Enum('REQUESTED', 'SEARCHING', 'ACCEPTED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='ride_status_enum'), nullable=False, comment='Current ride status'),
    sa.Column('pickup_lat', sa.Float(), nullable=False, comment='Pickup latitude'),
    sa.Column('pickup_lng', sa.Float(), nullable=False, comment='Pickup longitude'),
    sa.Column('pickup_address', sa.String(length=500), nullable=True, comment='Human-readable pickup address'),
    sa.Column('dropoff_lat', sa.Float(), nullable=False, comment='Dropoff latitude'),
    sa.Column('dropoff_lng', sa.Float(), nullable=False, comment='Dropoff longitude'),
    sa.Column('dropoff_address', sa.String(length=500), nullable=True, comment='Human-readable dropoff address'),
    sa.Column('estimated_fare', sa.Float(), nullable=True, comment='Estimated fare in cents (or currency units)'),
    sa.Column('distance', sa.Float(), nullable=True, comment='Total route distance in meters'),
    sa.Column('duration', sa.Float(), nullable=True, comment='Total route duration in seconds'),
    sa.Column('encoded_polyline', sa.Text(), nullable=True, comment='Encoded polyline representing the route geometry'),
    sa.Column('final_fare', sa.Float(), nullable=True, comment='Final fare after ride completion'),
    sa.Column('payment_status', sa.Enum('PENDING', 'AUTHORIZED', 'CAPTURED', 'REFUNDED', 'FAILED', name='payment_status_enum'), nullable=False, comment='Payment status: pending, authorized, captured, refunded, failed'),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True, comment='Stripe PaymentIntent ID'),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True, comment='Who cancelled: rider/driver/system'),
    sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='Reason for cancellation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When ride was requested'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last status update'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='When driver accepted'),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True, comment='When driver arrived at pickup'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When ride began'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When ride finished'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='When ride was cancelled'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index(op.f('ix_rides_rider_id'), 'rides', ['rider_id'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_rider_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
